### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by GizmoGoody** [bsileo/hubitat_poolcontroller#10]
@bsileo Here is a screenshot of the ST UI on my iPhone 11 Pro.

![20200710_131016000_iOS](https://user-images.githubusercontent.com/46235745/87217188-81e3ef00-c2fb-11ea-822b-586669987ec8.png)

Here are my issues with it:

Missing the AuxX circuit
Missing the Spa circuit
Are the top icons supposed to be round (not oval)?
What is the 72 indicating?
The font is too small
What are all of the -- supposed to indicate?
How can I tell if the pool or spa temp is current or last read?

**Comment by bsileo** [comment]
We don't have any control over round vs. oval icons - that's SmartThings being lame. 
Same for the Font size - not in my control.
72 is the Air Temp
The "--" are just supposed to be blank tiles. I guess on iOS is puts those dashes in. On Android these show up as blank. 
ST makes the UI very hard to configure dynamically for different pool setups.

Here is everything that is added, but if any of these children do not exist they are skipped in ST.  Note that you can also just go to the individual devices and not use the main "Pool" device with all this clutter on it. 

```
"airTemp","solarTemp","dummy","refresh",
                "setPoint-1","heatMode-1","temperature-1", "dummy-b-1", "dummy-b-1", "dummy-b-1",
                "setPoint-2","heatMode-2","temperature-2", "dummy-b-2", "dummy-b-2", "dummy-b-2",

                "saltLevel-1","saltRequired-1","superClorinate-1","superChlorHours-1","currentOutput-1","poolSetpoint-1","spaSetPoint-1","chlorStatus-1",
                "saltLevel-2","saltRequired-2","superClorinate-2","superChlorHours-2","currentOutput-2","poolSetpoint-2","spaSetPoint-2","chlorStatus-2",
                "Circuit 2 Switch","Circuit 3 Switch","Circuit 4 Switch","Circuit 5 Switch","Circuit 6 Switch","Circuit 7 Switch",
                "Circuit 8 Switch",
                "feature11","feature12","feature13","feature14","feature15","feature16","feature17","feature18"
```
[Aside...several items in the list here for why I moved to Hubitat!]

**Comment by bsileo** [comment]
Here is a view on Android:

![Screenshot_20200711-091020_SmartThings](https://user-images.githubusercontent.com/6116016/87224838-9c978180-c356-11ea-8743-1b1bad56c40a.jpg)

**Comment by bsileo** [comment]
Also, you can technically edit / change this layout.  Just edit what is included in your local copy of the Pool-Controller.groovy on your St hub in the [details section](https://github.com/bsileo/hubitat_poolcontroller/blob/master/devicetypes/bsileo/pool-controller.src/pool-controller.groovy#L120)

**Comment by GizmoGoody** [comment]
Ok, thanks. The 72 would be solartemp then, but I don’t have solar. Guess I can just delete that one.

**Comment by GizmoGoody** [comment]
For the groovy edits, I tried to change it to this

            details (
                "airTemp","refresh",
                "setPoint-1","heatMode-1","temperature-1"
                "setPoint-2","heatMode-2","temperature-2"
                "saltLevel-1","saltRequired-1","currentOutput-1","poolSetpoint-1","spaSetPoint-1","chlorStatus-1",
                "Circuit 5 Switch","Circuit 6 Switch","Circuit 2 Switch","Circuit 3 Switch","Circuit 4 Switch","Circuit 7 Switch",
                "Circuit 8 Switch",
                "feature11","feature12","feature13","feature14","feature15","feature16","feature17","feature18"
                )

...but got this when I tried to save...

```
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
script_dth_metadata_cd1ac6b5_7055_404d_8113_0dc21559855c: 123: expecting ')', found 'setPoint-2' @ line 123, column 17.
"setPoint-2","heatMode-2","temperature-2"
^

1 error
```

What did I mess up? Also, what do I need to put to see the AuxX circuit (e.g. "Circuit Aux")?

**Comment by bsileo** [comment]
I think you are missing a comma after "temperature-1"

I am not sure what the Circuit Aux is -Do you have this on the WebClient for NJPC?  I have to understand that as I do not think it is available in ST/Hubitat at this time.

**Comment by GizmoGoody** [comment]
Thanks. Yes, my Spillway is configured to the AuxX circuit which allows me to use the Solar button on the ET4 hard panel in place of the not-configured Solar.

I figured out that the air and solar temp tiles were ovals because you have them set to 2 wide by 1 tall. I changed all tiles to 2 x 2 and here is what it looks like.
![20200712_053219000_iOS](https://user-images.githubusercontent.com/46235745/87239698-f6379480-c3c6-11ea-8f87-6da80ea966a3.png)

**Comment by bsileo** [comment]
Thanks for the update on the icon appearance - a difference between Android and iOS I suppose. In general, there is no way to create intelligence in the way the UI is built in SmartThings, so I took the approach of creating all the child devices so each user would have control of things, and attempted this general UI. The path you have taken, adjusting it to your own needs is really the only way to get it specific to a given user that I know.

**Comment by bsileo** [comment]
I do not have solar or this configuration on my system. Are you able to control the AuxX button from the webClient UI in the PoolController? I need to get some details on what is happening when that is pressed so I can see about adding it to the SmartTHings side.   

Perhaps send me the output from:
http://server1:4200/state/all
http://server1:4200/config/all

Trying to understand where I would detect that setup and its current state.

**Comment by bsileo** [comment]
I just found this in my /config/all
```
{
"id": 20,
"name": "AUX EXTRA",
"nameId": 93,
"type": 0,
"isActive": true,
"freeze": false,
"showInFeatures": true,
"eggTimer": 0,
"macro": false
}
```
Is this the same Feature you are seeing connected to the Solar button?

**Comment by GizmoGoody** [comment]
Yes. Also, I do have a child device for it (Spillway) in ST, and yes it’s also available on the web client.

________________________________

**Comment by bsileo** [comment]
OK is that Child working to control it in ST?  If so then we are just missing it on the main PoolController device tiles?

**Comment by GizmoGoody** [comment]
Yes (just verified)

![C4199336-3A59-4A2F-B22F-35A6A6366E03](https://user-images.githubusercontent.com/46235745/87252635-7b539580-c429-11ea-8dab-2919b6837f2f.png)

**Comment by bsileo** [comment]
Can you look at that in https://graph.api.smartthings.com/device/list and tell me what the 'Device Network ID' is for the Pool (Spillway) device?

BTW - you can feel free to edit and rename these - only the Device Network ID matters to the code keeping updates flowing. I see you already figured out you can change the icons on them!

**Comment by GizmoGoody** [comment]
B827EB548DF6-feature-20

I tried to insert "feature20", but it didn't work

Also, I realized that I missed one of your requests above. Here are the state and config results.
[State.txt](https://github.com/bsileo/hubitat_poolcontroller/files/4910417/State.txt)
[Config.txt](https://github.com/bsileo/hubitat_poolcontroller/files/4910416/Config.txt)

**Comment by bsileo** [comment]
I just pushed an update to add support for going up to ID 20 for features. I had them going from 11-20.

[Code](https://github.com/bsileo/hubitat_poolcontroller/blob/master/devicetypes/bsileo/pool-controller.src/pool-controller.groovy)

**Comment by GizmoGoody** [comment]
Thanks. I updated from repo, set all the tiles back to 2x2 and then set up the tiles to this:

            details (
                "airTemp","Circuit 3 Switch","Circuit 4 Switch",
                "temperature-1","setPoint-1","heatMode-1",
                "temperature-2","setPoint-2","heatMode-2",
                "saltLevel-1","currentOutput-1","poolSetpoint-1",
                "Circuit 2 Switch","feature11","feature20",
                "Circuit 6 Switch","Circuit 1 Switch","refresh"
                )

It looks good.
![20200714_052608000_iOS](https://user-images.githubusercontent.com/46235745/87387707-24001300-c558-11ea-9681-e9fb19504990.png)
![20200714_052613000_iOS](https://user-images.githubusercontent.com/46235745/87387710-2498a980-c558-11ea-8c99-4e9ddc227871.png)

**Comment by bsileo** [comment]
Sweet glad it is working for you!
