### ISSUE TITLE
SmartThings App Migration

### ISSUE THREAD

**Issue by GizmoGoody** [bsileo/hubitat_poolcontroller#11]
@bsileo I just started receiving the notices to migrate to the new app. If I did, I assume your custom DTH would remain, but I would still only be able to use the Classic app to interact with the Pool things. Is that right? 

I’ve heard they’re going to remove IDE support eventually. Won’t that break this custom integration?

Are you considering writing a SmartApp for the new app?

**Comment by bsileo** [comment]
I believe this is correct that this will only work on the classic app.

I .not currently planning to work on a version for the new SmartThings environment.
