### ISSUE TITLE
Intellibrite not switching on/off?

### ISSUE THREAD

**Issue by johnny2678** [bsileo/hubitat_poolcontroller#13]
Hey Bsileo,

Not sure I've tested lights before so not sure if this is new or if it never worked for me, but I can't get lights to turn on/off using either the switch or the intellibrite controller device.

Everything else seems to be working. Parent device is updated and I can control the pump.  Just the lights

Not sure if this log section is relevant?  from bottom to top:

```
dev:5452020-09-09 09:09:08.626 pm errorCiurcuit update failed with code 408
dev:5452020-09-09 09:08:56.578 pm debugSend PUT to /state/circuit/setState with [id:2, state:1] and setCircuitCallback
dev:5452020-09-09 09:08:56.576 pm debugExecuting setCircuit with Pool (Lights) - 2 to 1
dev:5452020-09-09 09:08:56.570 pm debugGot ON Request from Pool (Lights)
```

def don't want to be that guy but minor typo in the last line

Anything ideas?  Super low priority

**Comment by bsileo** [comment]
I will have to test again but I think this is working with my intellibrites. This is in Hubitat right?

**Comment by johnny2678** [comment]
sorry, yes - hubitat.

does that error mean anything to you?
