### ISSUE TITLE
Newbie needs help!

### ISSUE THREAD

**Issue by gambler2841** [bsileo/hubitat_poolcontroller#17]
Hello,

I was able to get the pool controller up and running and connected to my Hubitat. From the dashboard I can control the pool and spa (temperature/jets, etc), but what comes into Hubitat doesn't seem like there is anything to control the temperature. It will just turn the spa on to the set temperature. I'm using Sharptools dashboard to try and control the pool/spa. Any help would be greatly appreciated!

**Comment by bsileo** [comment]
I believe this is resolved in the latest release so closing here. let me know if not!
