### ISSUE TITLE
Change the upnp device schema reference

### ISSUE THREAD

**Issue by rstrouse** [bsileo/hubitat_poolcontroller#20]
Can I get you to change the upnp schema you reference from `urn:schemas-upnp-org:device:PoolController:1` to `urn:schemas-tagyoureit-org:device:PoolController:1`.  We have implemented proper upnp handshaking and need to make sure we are not referencing a upnp.org device schema.

**Comment by bsileo** [comment]
I deployed this change and updated the code in HPM. It needs tested yet. I have to update my environments to the latest PoolController and work through that testing yet.
