### ISSUE TITLE
Consider using Hubitat Package Manager?

### ISSUE THREAD

**Issue by johnny2678** [bsileo/hubitat_poolcontroller#5]
This completely falls in the 'I am lazy and don't feel like manually installing a bunch of driver code' category.  Feel free to close, just wanted to put it out there for your consideration.

Some of the app developers I follow have started using [Hubitat Package Manager](https://github.com/dcmeglio/hubitat-packagemanager) to update their code.  Problem with Hubitat is there's no native github connectivity like ST.  So you have to check each app / device to see if there's updates.  

UX for this very much resembles existing ST / github integration except it's all in one step, instead of updating apps / drivers in 2 steps.  Plus you can configure it to notify the app on your phone where there are new Package updates.

**Comment by bsileo** [comment]
This is a good idea and I will look into it. Overall, I need to figure out how to restructure the repository to handle SmartThings and Hubitat github integration, so this would line up well with that effort.

**Comment by bsileo** [comment]
Now deployed within HPM!
