### ISSUE TITLE
Not discoverable

### ISSUE THREAD

**Issue by therapcat** [bsileo/hubitat_poolcontroller#7]
hi Brad, sorry for opening a new issue. I installed the poolController next and also the pool controller web client. I can't confirm if either are running. 

I've edited the config.json file in the poolController next to reflect my ST hub IP address. I'm not sure if that's the IP I should use or the IP of the Raspberry PI that is connected to my RS485 adapter.  

I had this all working on the 5.3.3 version before. 

I really just need this to show up in SmartThings. The app is there but the pool controller doesn't show up. 

Please advise.

**Comment by therapcat** [comment]
This is the output when I try to run this with NPM start:

hoobs@hoobs:~/nodejs-poolController-next $ npm start

> nodejs-poolController@6.0.0 start /home/hoobs/nodejs-poolController-next
> npm run build && node dist/app.js


> nodejs-poolController@6.0.0 build /home/hoobs/nodejs-poolController-next
> tsc

Init state for Pool Controller
info: Init http interface: SmartThings
error: Error initializing interface bindings: Error: watch /home/hoobs/nodejs-poolController-next/web/bindings/smartThings.json ENOENT
Error: listen EADDRINUSE 0.0.0.0:4200
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1351:14)
    at listenInCluster (net.js:1392:12)
    at doListen (net.js:1501:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:686:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodejs-poolController@6.0.0 start: `npm run build && node dist/app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodejs-poolController@6.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2020-05-26T22_22_48_373Z-debug.log
hoobs@hoobs:~/nodejs-poolController-next $ 
[1] 0:bash*                                                                                                            "hoobs" 15:23 26-May-20

**Comment by therapcat** [comment]
rebooted the whole thing. Re-ran it. Still not showing up in ST.  I'd add it manually but I don't know the MAC address for the Pool Controller? Is that just the MAC address for the Rasbperry PI? 

Init state for Pool Controller
info: Init http interface: SmartThings
error: Error initializing interface bindings: Error: watch /home/hoobs/nodejs-poolController-next/web/bindings/smartThings.json ENOENT                                                                                                                       
info: Server is now listening on 0.0.0.0:4200
info: Serial port: FAKE_PORT opened
info: Serial port: FAKE_PORT request to open succeeded without error

**Comment by bsileo** [comment]
This error:

> error: Error initializing interface bindings: Error: watch /home/hoobs/nodejs-poolController-next/web/bindings/smartThings.json ENOENT

There was a change on the controller side, config should now be: 

```
"fileName": "smartThings-Hubitat.json",
```

**Comment by bsileo** [comment]
And this looks like a problem - 

Error: listen EADDRINUSE 0.0.0.0:4200

Something else is on port 4200 already on your Pi?

**Comment by bsileo** [comment]
If you wind up trying to do it manually, then yes the MAC address of the PI running nodejs-poolController

**Comment by therapcat** [comment]
I think this was from the previous instance not loading all the way. I’ll reboot and try it again. I didn’t get this error after rebooting.

I’ll change the config to show this smartThings-Hubitat.json and hopefully I’ll be good.



On May 26, 2020, at 5:17 PM, Brad Sileo <notifications@github.com<mailto:notifications@github.com>> wrote:



And this looks like a problem -

Error: listen EADDRINUSE 0.0.0.0:4200

Something else is on port 4200 already on your Pi?

**Comment by therapcat** [comment]
Ok. I added it manually and it verified it. It also added the controller but there were 0 devices listed. Do I have to add those manually?

**Comment by bsileo** [comment]
What's showing up in your ST logs? Trying going to Configuration for the main device, change the logging level to "Trace"

**Comment by therapcat** [comment]
[MobilePresence Optional(com.smartthings 2020-05-23--20-22-01-187.log)](https://github.com/bsileo/hubitat_poolcontroller/files/4685750/MobilePresence.Optional.com.smartthings.2020-05-23--20-22-01-187.log)
[Video Optional(com.smartthings 2020-05-26--16-33-23-031.log)](https://github.com/bsileo/hubitat_poolcontroller/files/4685751/Video.Optional.com.smartthings.2020-05-26--16-33-23-031.log)
[Global Optional(com.smartthings 2020-05-25--20-39-29-185.log)](https://github.com/bsileo/hubitat_poolcontroller/files/4685752/Global.Optional.com.smartthings.2020-05-25--20-39-29-185.log)
[Global Optional(com.smartthings 2020-05-25--05-58-37-306.log)](https://github.com/bsileo/hubitat_poolcontroller/files/4685753/Global.Optional.com.smartthings.2020-05-25--05-58-37-306.log)
[Global Optional(com.smartthings 2020-05-22--18-02-57-310.log)](https://github.com/bsileo/hubitat_poolcontroller/files/4685754/Global.Optional.com.smartthings.2020-05-22--18-02-57-310.log)
[MobilePresence Optional(com.smartthings 2020-05-22--18-35-52-420.log)](https://github.com/bsileo/hubitat_poolcontroller/files/4685755/MobilePresence.Optional.com.smartthings.2020-05-22--18-35-52-420.log)
[MobilePresence Optional(com.smartthings 2020-05-25--22-17-34-307.log)](https://github.com/bsileo/hubitat_poolcontroller/files/4685756/MobilePresence.Optional.com.smartthings.2020-05-25--22-17-34-307.log)
[Video Optional(com.smartthings 2020-05-25--05-58-37-537.log)](https://github.com/bsileo/hubitat_poolcontroller/files/4685760/Video.Optional.com.smartthings.2020-05-25--05-58-37-537.log)







[Global Optional(com.smartthings 2020-05-26--15-30-03-465.log)](https://github.com/bsileo/hubitat_poolcontroller/files/4685743/Global.Optional.com.smartthings.2020-05-26--15-30-03-465.log)
[Video Optional(com.smartthings 2020-05-24--04-46-00-819.log)](https://github.com/bsileo/hubitat_poolcontroller/files/4685744/Video.Optional.com.smartthings.2020-05-24--04-46-00-819.log)
[Global Optional(com.smartthings 2020-05-23--20-22-01-186.log)](https://github.com/bsileo/hubitat_poolcontroller/files/4685745/Global.Optional.com.smartthings.2020-05-23--20-22-01-186.log)
[MobilePresence Optional(com.smartthings 2020-05-21--18-26-04-119.log)](https://github.com/bsileo/hubitat_poolcontroller/files/4685746/MobilePresence.Optional.com.smartthings.2020-05-21--18-26-04-119.log)
[MobilePresence Optional(com.smartthings 2020-05-24--20-41-06-864.log)](https://github.com/bsileo/hubitat_poolcontroller/files/4685747/MobilePresence.Optional.com.smartthings.2020-05-24--20-41-06-864.log)
[MobilePresence Optional(com.smartthings 2020-05-26--22-21-47-366.log)](https://github.com/bsileo/hubitat_poolcontroller/files/4685748/MobilePresence.Optional.com.smartthings.2020-05-26--22-21-47-366.log)
[Global Optional(com.smartthings 2020-05-24--16-50-00-122.log)](https://github.com/bsileo/hubitat_poolcontroller/files/4685749/Global.Optional.com.smartthings.2020-05-24--16-50-00-122.log)

**Comment by therapcat** [comment]
When I try to edit the pool controller, I named it "Pentair" I get an error "Error fetching device. Please try again."

**Comment by therapcat** [comment]
should I delete those logs? Not sure if there's any sensitive info there. But if you search Pentair in them, you can see an error 500 for com.smartthings.stclient

**Comment by bsileo** [comment]
I was looking for the ide logs from SmartThings. - From https://graph.api.smartthings.com/ide/logs

**Comment by therapcat** [comment]
![Screen Shot 2020-05-26 at 5 50 13 PM](https://user-images.githubusercontent.com/47578371/82964100-67d39480-9f79-11ea-8479-c79c6163ab84.png)
![Screen Shot 2020-05-26 at 5 49 20 PM](https://user-images.githubusercontent.com/47578371/82964117-71f59300-9f79-11ea-8998-185514f4253b.png)
![Screen Shot 2020-05-26 at 5 49 13 PM](https://user-images.githubusercontent.com/47578371/82964118-728e2980-9f79-11ea-83a3-939e88dd88ba.png)
![IMG_2218](https://user-images.githubusercontent.com/47578371/82964125-7752dd80-9f79-11ea-82ab-3e54ae4ab590.PNG)

**Comment by therapcat** [comment]
I re-added the controller, but it still gave 0 options for devices when adding. It didn't end up adding it because I already had the other one in there with the same name. But the issue is with pulling the configs from the pentair controller.  It isn't reading any of the devices.

**Comment by bsileo** [comment]
Agreed- your nodejs-poolController instance is not working right. Thats a prerequisite so you need to sort that first then get the SmartThings side going.  Best source of help on that is https://gitter.im/nodejs-poolController/Lobby

**Comment by bsileo** [comment]
Assuming this is resolved so closing.
