### ISSUE TITLE
Change / add custom Chlorinator attribute for saltLevel to INT?

### ISSUE THREAD

**Issue by johnny2678** [bsileo/hubitat_poolcontroller#9]
Hi @bsileo 

Went to create a Rule Machine alert to let me know when Salt level falls below 3600 and I couldn't do it.  See screenshot

![image](https://user-images.githubusercontent.com/8219743/87157230-eebfa080-c28b-11ea-8db4-e5ec79d78fc9.png)

Is it currently a string?  If so, could it be changed to INT or, if it's needed as STR elsewhere, add another INT attribute with the same value?

edit: hit enter too early

**Comment by bsileo** [comment]
This is fixed in the latest push of code!
